name: Push Docker image to custom registry

on:
  push:
    branches: [ azure ]
    paths:
      - 'Dockerfile'

jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: todoappmpt.azurecr.io
          username: todoappmpt
          password: gMicqQG9eXMIz3B7cIxeAImQpVdU4mBY+Eug3hPBAl+ACRBprJ/E

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: todoappmpt.azurecr.io/todoappmpt:v1
