name: Push Docker image to custom registry

on:
  push:
    branches:
      - azure

jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        uses: azure/docker-login@v1
        with:
          login-server: todoappmpt.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}}
          password: ${{ secrets.ACR_PASSWORD }}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: todoappmpt.azurecr.io/todoappmpt:v1
