name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Google Artifact Registry
          uses: docker/login-action@v1
          with:
            registry: us-docker.pkg.dev/pelagic-sorter-401721/todo-app-backend:latest
            username: _json_key
            password: ${{ secrets.GCP_SA_KEY }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: us-docker.pkg.dev/pelagic-sorter-401721/todo-app-backend:${{ github.sha }}
