name: CI/CD Pipeline

on:
  push:
    branches:
      - gcp


jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: pelagic-sorter-401721
            export_default_credentials: true

        - name: Login to Artifact Registry
          uses: docker/login-action@v1
          with:
            registry: us-central1-docker.pkg.dev
            username: _json_key
            password: ${{ secrets.GCP_SA_KEY }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: us-central1-docker.pkg.dev/pelagic-sorter-401721/todo-app-backend/todo-app-backend:latest
